### Say hello
# greet a stranger
GET http://localhost:3000/api/hello

### Say hello to Jane
# greet someone by name
GET http://localhost:3000/api/hello/Jane

### Login with name and password
# Authentication
# we send name and password and expect an access token
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "name": "Jane",
  "password": "password"

}


### Get profile via access token
# get user profile that belongs to the access token in the Authorization header
# asking the server, who am I?
GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjRlOWUyZmJhMjkzZmU1ZDU4NDFiYTYiLCJpYXQiOjE2NDkzMjMxNjB9.8ujAg6rL38fIkZECLusfaHK__cMeMyB2RniyDtE7c0U


### Login with GitHub authorization code
# authorization code provided by GitHub and expect access token back
POST http://localhost:3000/api/github-login
Content-Type: application/json

{
  "code": "github-authorization-code"
}

